sonar.organization=kellytacardosoleal1-design
sonar.projectKey=kellytacardosoleal1-design_open-color
sonar.projectName=open-color-teste-lyan
sonar.host.url=https://sonarcloud.io
sonar.token=SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

sonar.sources=.

# EXCLUSÃO COMPLETA: Bloqueia dependências externas, testes e arquivos duplicados
sonar.exclusions=node_modules/**, public/**, tests/**, builder/**, coverage/**, **/*.test.js, compile-templates.js, open-color.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info